[package]
name = "qrtransfer"
version = "0.1.0"
authors = ["lxu <lxu@junzhiam.com>"]
edition = "2018"

[dependencies]
qrcode = "*"
base64 = "*"
sha-1 = "*"
indexmap = "*"
quircs = "*"
image = "*"
brotli = "*"
wasm-bindgen = { version = "*", features = ["serde-serialize"] }
console_error_panic_hook = "*"
web-sys = { version = "*", features = [
    'Document',
    'Element',
    'HtmlElement',
    'HtmlInputElement',
    'FileReader',
    'File',
    'ProgressEvent',
    'FileList',
    'Node',
    'Window',
    'console',
] }
dioxus = { version = "*", features = ["web"] }
js-sys = "*"
